import { useState } from 'react'
import { ChevronRight } from 'lucide-react'
import IssueCard from './IssueCard'
import { Issue } from '../types/backbone'

interface Props {
  issues: Issue[]
}

export default function SelfCritiqueFooter({ issues }: Props) {
  const [expanded, setExpanded] = useState(false)

  return (
    <div className="animate-fade-slide-up mt-5 border-t border-white/[0.08] pt-4">
      {!expanded ? (
        <button
          className="w-full text-left group focus:outline-none focus:ring-2 focus:ring-[#10A37F80] rounded-lg"
          onClick={() => setExpanded(true)}
          aria-expanded={false}
          aria-label="Expand self-critique"
        >
          <div className="flex items-center gap-2 mb-2">
            <p className="text-[13px] font-medium text-[#AFAFAF] group-hover:text-[#ECECEC] transition-colors duration-150">
              Here's what to verify before using this
            </p>
            <ChevronRight
              size={14}
              className="text-[#8F8F8F] group-hover:text-[#ECECEC] transition-all duration-200 mt-px group-hover:translate-x-0.5"
            />
          </div>
          <ul className="space-y-1 mb-2 pl-1">
            {issues.map((issue, i) => (
              <li key={i} className="flex items-start gap-2 text-[13px] text-[#8F8F8F]">
                <span className="mt-1.5 w-1 h-1 rounded-full bg-[#8F8F8F] flex-shrink-0" />
                <span>{issue.title}</span>
              </li>
            ))}
          </ul>
          <p className="text-[11px] text-[#8F8F8F] italic">
            Generated by a separate evaluation pass · Always paired with reasoning
          </p>
        </button>
      ) : (
        <div className="animate-fade-slide-up">
          <p className="text-[13px] font-medium text-[#ECECEC] mb-4">
            {issues.length} issues flagged · Backbone caught these before you did.
          </p>
          <div className="space-y-3">
            {issues.map((issue, i) => (
              <IssueCard key={i} issue={issue} />
            ))}
          </div>
          <button
            className="mt-4 text-[13px] text-[#8F8F8F] hover:text-[#ECECEC] transition-colors duration-150 focus:outline-none focus:underline"
            onClick={() => setExpanded(false)}
            aria-label="Collapse self-critique"
          >
            Collapse
          </button>
        </div>
      )}
    </div>
  )
}
